[package]
name = "nes_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24.0"
mockall = "0.11.4"
rand = "0.8.5"
